//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template_4435
{
    using System;
    using System.Collections.Generic;
    
    public partial class zakazy
    {
        public string Id { get; set; }
        public string Код_заказа { get; set; }
        public string Дата_создания { get; set; }
        public string Код_клиента { get; set; }
        public string Услуги { get; set; }

        public zakazy() { }
        public zakazy(string id, string код_заказа, string дата_создания, string код_клиента, string услуги)
        {
            Id = id;
            Код_заказа = код_заказа;
            Дата_создания = дата_создания;
            Код_клиента = код_клиента;
            Услуги = услуги;
        }
    }
}
